### ISSUE TITLE
Particles way too small after 1.12.1

### ISSUE THREAD

**Issue by Animoticons** [Shadnix-was-taken/BeatSaber-ParticleOverdrive#5]
I'm not sure if you can do anything about it, but since the 1.12.1 Multiplayer Update the Particles are really small. So small, that cranking up the percentage in ParticleOverdrive has almost no impact.
It would be awesome if there was a possibility to change the particle back to the original.

Thanks for your awesome mod and have a nice 2021!

**Comment by Shadnix-was-taken** [comment]
Added options to change the size of particles. Released with version 1.8.0, now available on the Github release page.
